export const GET_BURGER_INGREDIENTS_REQUEST = 'GET_BURGER_INGREDIENTS_REQUEST';
export const GET_BURGER_INGREDIENTS_SUCCESS = 'GET_BURGER_INGREDIENTS_SUCCESS';
export const GET_BURGER_INGREDIENTS_FAILED = 'GET_BURGER_INGREDIENTS_FAILED';

export const ADD_CONSTRUCTOR_INGREDIENT = 'ADD_CONSTRUCTOR_INGREDIENT';
export const DELETE_CONSTRUCTOR_INGREDIENT = 'DELETE_CONSTRUCTOR_INGREDIENT';
export const INCREASE_CONSTRUCTOR_COUNT = 'INCREASE_CONSTRUCTOR_COUNT';
export const DECREASE_CONSTRUCTOR_COUNT = 'DECREASE_CONSTRUCTOR_COUNT';
export const ADD_CONSTRUCTOR_BUN = 'ADD_CONSTRUCTOR_BUN';
export const UPDATE_CONSTRUCTOR_INGREDIENTS = 'UPDATE_CONSTRUCTOR_INGREDIENTS';

export const ADD_BURGER_INGREDIENT_INFO = 'ADD_BURGER_INGREDIENT_INFO';

export const GET_ORDER_REQUEST = 'GET_ORDER_REQUEST';
export const GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS';
export const GET_ORDER_FAILED = 'GET_ORDER_FAILED';

export const CLEAR_BURGER_INGREDIENT_INFO = 'CLEAR_CURRENT_INGREDIENT_INFO';
export const CLEAR_ORDER = 'CLEAR_ORDER';
