export const GET_ALL_INGREDIENTS_REQUEST = 'GET_ALL_INGREDIENTS_REQUEST';
export const GET_ALL_INGREDIENTS_SUCCESS = 'GET_ALL_INGREDIENTS_SUCCESS';
export const GET_ALL_INGREDIENTS_FAILED = 'GET_ALL_INGREDIENTS_FAILED';

export const GET_CURRENT_INGREDIENTS = 'GET_ALL_INGREDIENTS';

export const GET_CURRENT_INGREDIENT = 'GET_ALL_INGREDIENT';

export const GET_ORDER_REQUEST = 'GET_ORDER_REQUEST';
export const GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS';
export const GET_ORDER_FAILED = 'GET_ORDER_FAILED';

export const CLEAR_CURRENT_INGREDIENT_INFO = 'CLEAR_CURRENT_INGREDIENT_INFO';
export const CLEAR_ORDER = 'CLEAR_ORDER';
